config/routes.rb
Firstfm::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :stations do
    resources :streams
  end

  get 'latest' => 'stations#latest'

  put 'favourite/:id' => 'favourites#favourite', :as => :favourite
  put 'unfavourite/:id' => 'favourites#unfavourite', :as => :unfavourite

  root :to => 'stations#index'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :station_id, :user_id

  belongs_to :station
  belongs_to :user
  
end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :description, :homepage_url, :name

  validates :name, presence: true, :length => { :minimum => 2 }

  has_many :streams, :dependent => :destroy
  has_many :favourites

end

app/models/stream.rb
class Stream < ActiveRecord::Base
  attr_accessible :name, :url

  belongs_to :station
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :favourites
  has_many :stations, :through => :favourites
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  before_filter :authenticate_user!

  def favourite
    @station = Station.find(params[:id])
    current_user.stations << @station
    redirect_to stations_path, :notice => "#{@station.name} added to favourites"
  end

  def unfavourite
    @station = Station.find(params[:id])
    fav = current_user.favourites.find_by_station_id(params[:id])
    fav.destroy
    redirect_to stations_path, :notice => "#{@station.name} removed from favourites"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    stations_path
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @stations = Station.all    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stations }
    end
  end

  def latest
    #shows all in past day
    @stations = Station.where(:created_at => (Time.now.beginning_of_day - 1.day)..Time.now)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @station = Station.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.json
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(params[:station])

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render json: @station, status: :created, location: @station }
      else
        format.html { render action: "new" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stations/1
  # PUT /stations/1.json
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url }
      format.js
    end
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  
  respond_to :html

  before_filter :authenticate_user!, :except => [:index]

  def index
    @station = Station.find(params[:station_id])
    @streams = @station.streams
  end

  def new
    @station = Station.find(params[:station_id])
    @stream = @station.streams.build
  end

  def create
    @station = Station.find(params[:station_id])
    @stream = @station.streams.build(params[:stream])
    if @stream.save
      redirect_to station_streams_path(@station)
    else
      render 'new'
    end
  end

  def destroy
    @station = Station.find(params[:station_id])
    @stream = @station.streams.find(params[:id])
    @stream.destroy
    redirect_to station_streams_path(@station)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'digest/md5'

  def gravatar_image_for(email, size=100) 
    image_tag(
    "http://www.gravatar.com/avatar/
    #{Digest::MD5::hexdigest(email)}?s=#{size}")
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firstfm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= image_tag 'logo.png', :style => "width:100px; float:right;" %>

  <% if user_signed_in? %>
    <%= gravatar_image_for(current_user.email) %>
    <p>hello <%= link_to current_user.email, edit_user_registration_path %> | <%= link_to 'sign out', destroy_user_session_path, :method => 'delete' %></p>
  <% else %>
    <p><%= link_to 'sign in', user_session_path %> </p>
  <% end %>

  <hr/>
  <%= yield %>

</body>
</html>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :homepage_url %><br />
    <%= f.text_field :homepage_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/destroy.js.erb
$('#station_<%=@station.id%>').remove();

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Homepage url</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <% if current_user %>
      <th></th>
    <% end %>
  </tr>

<% @stations.each do |station| %>
  <tr id = "station_<%= station.id %>">
    <td><%= station.name %></td>
    <td><%= station.description %></td>
    <td><%= station.homepage_url %></td>
    <td><%= link_to 'Streams', station_streams_path(station) %></td>
    <td><%= link_to 'Show', station %></td>
    <td>
    <% if current_user %>
      <% if current_user.stations.include?(station) %>
        <%= button_to 'Unfavourite', unfavourite_path(station), :method => :put %>
      <% else %>
        <%= button_to 'Favourite', favourite_path(station), :method => :put %>
      <% end %>
    <% end %> 
    </td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New station', new_station_path %>

app/views/stations/latest.html.erb
<h1>Latest Stations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Homepage url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.name %></td>
    <td><%= station.description %></td>
    <td><%= station.homepage_url %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Station: <%= @station.name  %></h1>
<p>
  <b>Description:</b>
  <%= @station.description %>
</p>

<p>
  <b>Homepage url:</b>
  <%= @station.homepage_url %>
</p>

<h2>Streams</h2>
<%= render 'streams/streams', :streams => @station.streams %>

<hr/>


<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/streams/_streams.html.erb
<table>
  <tr>
    <th>Name</th>    
    <th>Url</th>
    <th></th>
  </tr>

<% streams.each do |stream| %>
  <tr>
    <td><%= stream.name %></td>
    <td><%= stream.url %></td>    
    <td><%= link_to 'Destroy', station_stream_path(@station, stream), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/streams/index.html.erb
<h1>Listing <%= @station.name %> streams</h1>

<%= render 'streams', :streams => @streams %>

<br />

<%= link_to 'New stream', new_station_stream_path(@station) %>

app/views/streams/new.html.erb
<h1>New stream</h1>

<%= form_for @stream, :url => station_streams_path(@station) do |f| %>
  <% if @stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>
      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', station_streams_path(@station) %>